# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "795906969dfaa71d3eb9044eb6c11ff3"
application_url = "https://chose-bryan-ministries-steady.trycloudflare.com"
embedded = true
name = "GG Connector"
handle = "gg-connector"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://chose-bryan-ministries-steady.trycloudflare.com/auth/callback",
  "https://chose-bryan-ministries-steady.trycloudflare.com/auth/shopify/callback",
  "https://chose-bryan-ministries-steady.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "pop-things-au.myshopify.com"
automatically_update_urls_on_dev = true
