# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a4d1fa8258a167ba9eb5a86de47d739f"
application_url = "https://reg-nation-thats-adopt.trycloudflare.com"
embedded = true
name = "Rareport Product Importer"
handle = "rareport-product-import"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_inventory, read_products, write_product_listings, write_files"

[auth]
redirect_urls = [
  "https://reg-nation-thats-adopt.trycloudflare.com/auth/callback",
  "https://reg-nation-thats-adopt.trycloudflare.com/auth/shopify/callback",
  "https://reg-nation-thats-adopt.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "pop-things-au.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
